import 'package:hundred_climbs/src/models/enums.dart';

//  @formatter:off
class Constants {
  static const grades = {
    GradingStyleEnum.french: [
      '4',
      '5a',
      '5a+',
      '5b',
      '5b+',
      '5c',
      '5c+',
      '6a',
      '6a+',
      '6b',
      '6b+',
      '6c',
      '6c+',
      '7a',
      '7a+',
      '7b',
      '7b+',
      '7c',
      '7c+',
      '8a',
      '8a+',
      '8b',
      '8b+',
      '8c',
      '8c+',
    ],
    GradingStyleEnum.polish: [
      'IV+',
      'V-',
      'V',
      'V+',
      'VI-',
      'VI',
      'VI+',
      'VI.1',
      'VI.1+',
      'VI.2',
      'VI.2+',
      'VI.3',
      'VI.3+',
      'VI.4',
      'VI.4+',
      'VI.5',
      'VI.5+'
    ]
  };
  static const defaultTags = [
    'crack',
    'crimp',
    'downclimb',
    'dyno',
    'epic',
    'fall',
    'friction',
    'gaston',
    'guppy',
    'heel-toe',
    'hook',
    'jib',
    'jug',
    'knee bar',
    'long',
    'low-angle',
    'mono',
    'natural features',
    'naturals',
    'nub',
    'overgraded',
    'overhang',
    'pinchers',
    'problem',
    'project',
    'redpoint',
    'roof',
    'rose',
    'side pull',
    'sit start',
    'slab',
    'sloper',
    'smearing',
    'sprag',
    'technical',
    'tendu',
    'thrutching',
    'toe hook',
    'traverse',
    'tufa',
    'undergraded',
  ];
}

//   @formatter:on
